"""
Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
Triangle 	  	Tn=n(n+1)/2 	  	1, 3, 6, 10, 15, ...
Pentagonal 	  	Pn=n(3n−1)/2 	  	1, 5, 12, 22, 35, ...
Hexagonal 	  	Hn=n(2n−1) 	  	1, 6, 15, 28, 45, ...

It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.

https://projecteuler.net/problem=45
"""


import argparse


def get_args():
    # noinspection PyTypeChecker
    argparse.ArgumentParser(
        description='Find the next triangle number that is also pentagonal and hexagonal.',
        formatter_class=argparse.ArgumentDefaultsHelpFormatter)


def main():
    get_args()
    tri_nums = {i * (i + 1) // 2 for i in range(286, 100000)}
    pen_nums = {i * (3 * i - 1) // 2 for i in range(166, 100000)}
    hex_nums = {i * (2 * i - 1) for i in range(144, 100000)}
    print(min(tri_nums.intersection(pen_nums).intersection(hex_nums)))


if __name__ == '__main__':
    main()
