"""
Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
Triangle 	  	Tn=n(n+1)/2 	  	1, 3, 6, 10, 15, ...
Pentagonal 	  	Pn=n(3n−1)/2 	  	1, 5, 12, 22, 35, ...
Hexagonal 	  	Hn=n(2n−1) 	  	1, 6, 15, 28, 45, ...

It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.

https://projecteuler.net/problem=45
"""


import utils


def main():
    tri_nums = utils.triangle_nums(286, 100000)
    pen_nums = utils.pentagonal_nums(166, 100000)
    hex_nums = utils.hexagonal_nums(144, 100000)
    print(min(tri_nums & pen_nums & hex_nums))


if __name__ == '__main__':
    main()
