"""
Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten pentagonal numbers are:

1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 − 22 = 48, is not pentagonal.

Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal and D = |Pk − Pj|
is minimised; what is the value of D?

https://projecteuler.net/problem=44
"""


from sys import maxsize

from utils import pentagonal_nums


def main():
    nums = pentagonal_nums(1, 10000)
    min_num = maxsize
    for i in (sorted_nums := sorted(nums)):
        for j in sorted_nums:
            if j > i:
                break
            if i + j in nums and i - j in nums:
                min_num = min(min_num, i - j)
    print(min_num)


if __name__ == '__main__':
    main()
