"""
Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten pentagonal numbers are:

1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 − 22 = 48, is not pentagonal.

Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal and D = |Pk − Pj|
is minimised; what is the value of D?

https://projecteuler.net/problem=44
"""


import argparse

from itertools import product


def get_args():
    # noinspection PyTypeChecker
    argparse.ArgumentParser(
        description='Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are '
                    'pentagonal and D = |Pk − Pj| is minimised; what is the value of D?',
        formatter_class=argparse.ArgumentDefaultsHelpFormatter)


def main():
    get_args()
    nums = {i * (3 * i - 1) // 2 for i in range(1, 10000)}
    print(min(j - i for i, j in product(nums, nums) if j > i and i + j in nums and j - i in nums))


if __name__ == '__main__':
    main()
