import argparse

from itertools import product


def get_args():
    # noinspection PyTypeChecker
    parser = argparse.ArgumentParser(
        description='How many distinct terms are in the sequence generated by a^b for 2 ≤ a ≤ n and 2 ≤ b ≤ n?',
        formatter_class=argparse.ArgumentDefaultsHelpFormatter)
    parser.add_argument('n', type=int, help='Upper limit (inclusive)')
    return parser.parse_args()


def main():
    args = get_args()
    print(len({i ** j for i, j in product(range(2, args.n + 1), range(2, args.n + 1))}))


if __name__ == '__main__':
    main()
